[package]
name = "util"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.13", features = ["image"] }
serde = { version = "1.0", features = ["derive"] }
num-traits = "0.2"
gset = "1.1"
dotenv = "0.15"
tap = "1.0"